package com.electrazoom.protoble.example;

import org.freedesktop.dbus.exceptions.DBusException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Date;

/**
 * Example Server with a main. Implements an interface defined by the hello.proto found in the
 * :example-api-hello module. The HelloWorldServiceRpc and HelloWoWorldServiceRpcServer are
 * generated by the electrazoom code generator. The Code Generator is launched by the
 * Google Protobuf Gradle Plugin and protoc.
 *
 * use the main to launch the server which will respond to the messages
 */
public class HelloServer implements HelloWorldRpc {
    private static final Logger LOG = LoggerFactory.getLogger(HelloServer.class);

    @Override
    public Hello.Greeting helloWorld(Hello.Introduction in) {
        Hello.Greeting.Builder greeting = Hello.Greeting.newBuilder();
        greeting.setTimesttamp(System.currentTimeMillis());
        greeting.setGreeting("hey, " + in.getSalutation() + ", " +
                in.getName());
        return greeting.build();
    }

    @Override
    public Hello.TimeResponse getTime(Hello.TimeRequest in) {
        return Hello.TimeResponse.newBuilder().setFormattedTime(new Date() + "").build();
    }

    @Override
    public void onConnect(String characteristic) {
        LOG.info("Connected to {}", characteristic);
    }

    @Override
    public void onError(String source, String message) {
        LOG.error("Error {} with {}", message, source);
    }

    private void start() throws DBusException, InterruptedException {
        HelloWorldRpcServer serviceRpc = new HelloWorldRpcServer(this);
        serviceRpc.startService();
    }

    public static void main(String... args) {
        HelloServer server = new HelloServer();
        try {
            server.start();
        } catch (DBusException e) {
            LOG.error("DBus error",e );
        } catch (InterruptedException e) {
            LOG.info("Stopped");
        }
    }
}
