use_frameworks!

platform :ios, '9.0'

target 'ProtoBLEiOS_Example' do
  pod 'ProtoBLEiOS', :path => '../'

  target 'ProtoBLEiOS_Tests' do
    inherit! :search_paths

  end
end

pod 'SwiftProtobuf', '~> 1.0'
